[package]
name = "rust_ssfi"
version = "0.1.0"
authors = ["Christopher Edelmaier <christopher.edelmaier@gmail.com>"]

[dependencies]
rand = "*"

[dependencies.comm]
git = "https://github.com/mahkoh/comm"
